USE BD046930

CREATE TABLE Produto
(
Id INT PRIMARY KEY IDENTITY(1,1),
Nome VARCHAR(200) NOT NULL,
Descricao VARCHAR(200) NOT NULL,
Valor DECIMAL NOT NULL,
Estoque INT NOT NULL,
CodigoBarra VARCHAR(50) NOT NULL
)
SELECT * FROM PRODUTO